  _target_: src.model.dinov2.CustomDINOv2
  model_name: dinov2_vitl14
  model: 
    _target_: torch.hub.load
    repo_or_dir: facebookresearch/dinov2
    model: dinov2
  token_name: x_norm_clstoken
  descriptor_width_size: 640
  image_size: 224
  chunk_size: 16